/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casinò;

import cards.BlackJack;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import myslotmachine.SlotMachineGUI;

/**
 *
 * @author ricpi
 */
public class MainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        aggiornaCredito();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Credit = new javax.swing.JLabel();
        bingoJB = new javax.swing.JButton();
        briscolaBJ = new javax.swing.JButton();
        pokerJB = new javax.swing.JButton();
        WheelJB = new javax.swing.JButton();
        B_account = new javax.swing.JButton();
        Ippica2 = new javax.swing.JButton();
        BlackJackGame = new javax.swing.JButton();
        Ippica = new javax.swing.JButton();
        SlotMachine = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1270, 740));
        setMinimumSize(new java.awt.Dimension(1270, 740));
        setPreferredSize(new java.awt.Dimension(1270, 750));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        Credit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Credit.setForeground(new java.awt.Color(255, 204, 51));
        Credit.setText("0,00€");
        jPanel1.add(Credit);
        Credit.setBounds(1160, 10, 50, 30);

        bingoJB.setBorderPainted(false);
        bingoJB.setContentAreaFilled(false);
        bingoJB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 56_1.png"))); // NOI18N
        bingoJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bingoJBActionPerformed(evt);
            }
        });
        jPanel1.add(bingoJB);
        bingoJB.setBounds(110, 560, 340, 150);

        briscolaBJ.setBorderPainted(false);
        briscolaBJ.setContentAreaFilled(false);
        briscolaBJ.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 59 (1).png"))); // NOI18N
        briscolaBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                briscolaBJActionPerformed(evt);
            }
        });
        jPanel1.add(briscolaBJ);
        briscolaBJ.setBounds(910, 120, 340, 150);

        pokerJB.setBorderPainted(false);
        pokerJB.setContentAreaFilled(false);
        pokerJB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 58.png"))); // NOI18N
        pokerJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokerJBActionPerformed(evt);
            }
        });
        jPanel1.add(pokerJB);
        pokerJB.setBounds(110, 120, 340, 150);

        WheelJB.setActionCommand("");
        WheelJB.setBorderPainted(false);
        WheelJB.setContentAreaFilled(false);
        WheelJB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WheelJB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 60.png"))); // NOI18N
        WheelJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelJBActionPerformed(evt);
            }
        });
        jPanel1.add(WheelJB);
        WheelJB.setBounds(910, 560, 340, 150);

        B_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        B_account.setContentAreaFilled(false);
        B_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_accountActionPerformed(evt);
            }
        });
        jPanel1.add(B_account);
        B_account.setBounds(1200, 0, 46, 47);

        Ippica2.setContentAreaFilled(false);
        Ippica2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 57.png"))); // NOI18N
        Ippica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ippica2ActionPerformed(evt);
            }
        });
        jPanel1.add(Ippica2);
        Ippica2.setBounds(710, 340, 540, 150);

        BlackJackGame.setContentAreaFilled(false);
        BlackJackGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BlackJackGame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 52.png"))); // NOI18N
        BlackJackGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackJackGameActionPerformed(evt);
            }
        });
        jPanel1.add(BlackJackGame);
        BlackJackGame.setBounds(510, 120, 340, 150);

        Ippica.setContentAreaFilled(false);
        Ippica.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 53.png"))); // NOI18N
        Ippica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IppicaActionPerformed(evt);
            }
        });
        jPanel1.add(Ippica);
        Ippica.setBounds(110, 340, 550, 150);

        SlotMachine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 55 (1).png"))); // NOI18N
        SlotMachine.setContentAreaFilled(false);
        SlotMachine.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 56.png"))); // NOI18N
        SlotMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotMachineActionPerformed(evt);
            }
        });
        jPanel1.add(SlotMachine);
        SlotMachine.setBounds(500, 550, 362, 168);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 51.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1250, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1250, 730);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Group 30 (1).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1250, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void aggiornaCredito() {
         try (BufferedReader br = new BufferedReader(new FileReader("accountTemp.txt"))) {
            String riga = br.readLine();
            System.out.println(riga);
            if (riga != null && !riga.trim().isEmpty()) {
                String[] dividi = riga.split(",");
                if (dividi.length == 3) {
                    int credito = Integer.parseInt(dividi[2]);
                    System.out.println("Contenuto dividi:" + dividi[2]);
                    Credit.setText(credito + "€");

                    // Aggiorna il file "input.txt"
                    String filePath = "input.txt";
                    String nome = dividi[0];
                    String password = dividi[1];
                    String nuovoCredito = String.valueOf(credito);

                    List<String> righe = new ArrayList<>();
                    boolean trovato = false;

                    // Legge il file "input.txt"
                    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
                        String linea;
                        while ((linea = reader.readLine()) != null) {
                            String[] parti = linea.split(",");
                            if (parti[0].equals(nome) && parti[1].equals(password)) {
                                righe.add(nome + "," + password + "," + nuovoCredito);
                                trovato = true;
                            } else {
                                righe.add(linea);
                            }
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    // Scrive le righe aggiornate nel file "input.txt"
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
                        for (String rigaFile : righe) {
                            writer.write(rigaFile);
                            writer.newLine();
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    if (trovato) {
                        System.out.println("Credito aggiornato con successo.");
                    } else {
                        System.out.println("Utente non trovato.");
                    }

                } else {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "Formato della riga non valido: " + riga);
                }
            } else {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "La riga letta è nulla o vuota.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "File non trovato", ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "Errore di input/output", ex);
        }
    }

    private void B_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_accountActionPerformed
        this.dispose();
        Account account = new Account();
        account.setVisible(true);
    }//GEN-LAST:event_B_accountActionPerformed

    private void BlackJackGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackJackGameActionPerformed
        this.dispose();
        new BlackJack();        
    }//GEN-LAST:event_BlackJackGameActionPerformed

    private void IppicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IppicaActionPerformed
       try {
            this.dispose();
            Ippica ippica = new Ippica();
            ippica.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IppicaActionPerformed

    private void SlotMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotMachineActionPerformed
        try {
            this.dispose();
            SlotMachineGUI slot=new SlotMachineGUI();
            slot.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SlotMachineActionPerformed

    private void Ippica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ippica2ActionPerformed
        try {
            this.dispose();
            Ippica ippica = new Ippica();
            ippica.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Ippica2ActionPerformed

    private void pokerJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokerJBActionPerformed
        nonDisp na=new nonDisp();
        na.setVisible(true);
    }//GEN-LAST:event_pokerJBActionPerformed

    private void briscolaBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_briscolaBJActionPerformed
        nonDisp na=new nonDisp();
        na.setVisible(true);
    }//GEN-LAST:event_briscolaBJActionPerformed

    private void bingoJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bingoJBActionPerformed
        nonDisp na=new nonDisp();
        na.setVisible(true);
    }//GEN-LAST:event_bingoJBActionPerformed

    private void WheelJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelJBActionPerformed
        nonDisp na=new nonDisp();
        na.setVisible(true);
    }//GEN-LAST:event_WheelJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_account;
    private javax.swing.JButton BlackJackGame;
    private javax.swing.JLabel Credit;
    private javax.swing.JButton Ippica;
    private javax.swing.JButton Ippica2;
    private javax.swing.JButton SlotMachine;
    private javax.swing.JButton WheelJB;
    private javax.swing.JButton bingoJB;
    private javax.swing.JButton briscolaBJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pokerJB;
    // End of variables declaration//GEN-END:variables
}
