/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casinò;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import myslotmachine.SlotMachineGUI;

/**
 *
 * @author ricpi
 */
public class MainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        aggiornaCredito();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Credit = new javax.swing.JLabel();
        B_account = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        B_blackjack = new javax.swing.JButton();
        B_blackjack1 = new javax.swing.JButton();
        Slot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(57, 57, 57));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Credit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Credit.setForeground(new java.awt.Color(255, 204, 51));
        Credit.setText("0,00€");

        B_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        B_account.setContentAreaFilled(false);
        B_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_accountActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(255, 255, 255)
                .addComponent(Credit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_account)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Credit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(B_account))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        B_blackjack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_blackjack.setText("Blackjack");
        B_blackjack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_blackjackActionPerformed(evt);
            }
        });

        B_blackjack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_blackjack1.setText("Ippica");
        B_blackjack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_blackjack1ActionPerformed(evt);
            }
        });

        Slot.setText("Slot");
        Slot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_blackjack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_blackjack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(Slot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(B_blackjack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Slot)))
                .addGap(77, 77, 77)
                .addComponent(B_blackjack1)
                .addGap(0, 433, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void aggiornaCredito() {
         try (BufferedReader br = new BufferedReader(new FileReader("accountTemp.txt"))) {
            String riga = br.readLine();
            System.out.println(riga);
            if (riga != null && !riga.trim().isEmpty()) {
                String[] dividi = riga.split(",");
                if (dividi.length == 3) {
                    int credito = Integer.parseInt(dividi[2]);
                    System.out.println("Contenuto dividi:" + dividi[2]);
                    Credit.setText(credito + "€");

                    // Aggiorna il file "input.txt"
                    String filePath = "input.txt";
                    String nome = dividi[0];
                    String password = dividi[1];
                    String nuovoCredito = String.valueOf(credito);

                    List<String> righe = new ArrayList<>();
                    boolean trovato = false;

                    // Legge il file "input.txt"
                    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
                        String linea;
                        while ((linea = reader.readLine()) != null) {
                            String[] parti = linea.split(",");
                            if (parti[0].equals(nome) && parti[1].equals(password)) {
                                righe.add(nome + "," + password + "," + nuovoCredito);
                                trovato = true;
                            } else {
                                righe.add(linea);
                            }
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    // Scrive le righe aggiornate nel file "input.txt"
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
                        for (String rigaFile : righe) {
                            writer.write(rigaFile);
                            writer.newLine();
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    if (trovato) {
                        System.out.println("Credito aggiornato con successo.");
                    } else {
                        System.out.println("Utente non trovato.");
                    }

                } else {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "Formato della riga non valido: " + riga);
                }
            } else {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "La riga letta è nulla o vuota.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "File non trovato", ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, "Errore di input/output", ex);
        }
    }

    private void B_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_accountActionPerformed
        this.dispose();
        Account account = new Account();
        account.setVisible(true);
    }//GEN-LAST:event_B_accountActionPerformed

    private void B_blackjackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_blackjackActionPerformed
        this.dispose();
        BlackJackGame black = new BlackJackGame();
        black.setVisible(true);
    }//GEN-LAST:event_B_blackjackActionPerformed

    private void B_blackjack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_blackjack1ActionPerformed
        try {
            this.dispose();
            Ippica ippica = new Ippica();
            ippica.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_B_blackjack1ActionPerformed

    private void SlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotActionPerformed
        try {
            this.dispose();
            SlotMachineGUI slot=new SlotMachineGUI();
            slot.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_SlotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_account;
    private javax.swing.JButton B_blackjack;
    private javax.swing.JButton B_blackjack1;
    private javax.swing.JLabel Credit;
    private javax.swing.JButton Slot;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
